config/routes.rb
Rails.application.routes.draw do
  root 'user_registers#new'
  # config/routes.rb
  resources :user_registers do
    member do
      get 'confirm_delete'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_register.rb
class UserRegister < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :email, presence: true 
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, if: -> { email.present? }
  validates :phone_number, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z/, message: "must be 10 digits" },if: -> { email.present? }
  validates :subject, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_registers_controller.rb
class UserRegistersController < ApplicationController
  def index 
    @user_registers = UserRegister.all
    @user_register = UserRegister.new  
  end
  def new
    @user_register = UserRegister.new
    @subjects = [
      ['Choose option', "", {disabled: true, selected: true}],
      ["Scrum", "Scrum"],
      ["Ruby on Rails", "Ruby on Rails"],
      ["TDD", "TDD"],
      ["CSS", "CSS"],
      ["Storytelling", "Storytelling"],
    ]
  end

  def create
    @user_register = UserRegister.new(user_register_params)
    if @user_register.save
      redirect_to user_registers_path, notice: 'User was successfully created.'
    else
    @subjects = [
      ['Choose option', "", {disabled: true, selected: true}],
      ["Scrum", "Scrum"],
      ["Ruby on Rails", "Ruby on Rails"],
      ["TDD", "TDD"],
      ["CSS", "CSS"],
      ["Storytelling", "Storytelling"],
    ]
      render :new, status: :unprocessable_entity
    end
  end

def confirm_delete
  @user_register = UserRegister.find(params[:id])
  render partial: 'modal/confirm_delete', locals: { user_register: @user_register }
end

def destroy
    @user_register = UserRegister.find(params[:id])
    @user_register.destroy
    respond_to do |format|
      format.html { redirect_to user_registers_path, notice: 'User was successfully deleted.' }
    end
end
  private
  def user_register_params
    params.require(:user_register).permit(:first_name, :last_name, :birthday, :gender, :email, :phone_number, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_registers_helper.rb
module UserRegistersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Register-ROR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css">
    <link rel="icon" href="<%= asset_path 'pen.png' %>" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= turbo_frame_tag "modal" %>
    <%= yield %>
  </body>
</html>

app/views/modal/_confirm_delete.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal-style">
    <div class="box-style">
      <h1>Confirm Delete</h1>
      <p>Are you sure you want to delete <%= @user_register.first_name %>?</p>
      <%= button_to 'Yes, Delete', user_register_path(@user_register), method: :delete, data: { turbo_frame: '_top' }, class: 'button-style delete' %>
      <%= link_to 'Cancel', '#', class: 'button-style cancel', data: { action: 'modal#close' } %>
    </div>
  </div>
<% end %>

app/views/user_registers/_gridCardInfo.html.erb
<div class="grid-content">
  <% @user_registers.each do |user_register| %>
    <div class="card">
      <div class="logo-card">
        <%= image_tag 'ODT.svg', alt: 'User Image', class: 'card-image' %>
      </div>
      <div class="card-info">
        <div class="card-content">
          <span class="head-text">Name:</span>
          <p class="sub-text"><span><%= user_register.first_name %></span>
            <span><%= user_register.last_name %></span></p>
        </div>
        <div class="card-content">
          <span class="head-text">Birthday:</span>
          <p class="sub-text"><%= user_register.birthday %></p>
        </div>
        <div class="card-content">
          <span class="head-text">Gender:</span>
          <p class="sub-text"><%= user_register.gender %></p>
        </div>
        <div class="card-content">
          <span class="head-text">Email:</span>
          <p class="sub-text"><%= user_register.email %></p>
        </div>
        <div class="card-content">
          <span class="head-text">Phone Number:</span>
          <p class="sub-text"><%= user_register.phone_number %></p>
        </div>
        <div class="card-content">
          <span class="head-text">Subject:</span>
          <p class="sub-text"><%= user_register.subject %></p>
        </div>
        <div class="btn-group">
          <%= button_to 'Delete', confirm_delete_user_register_path(user_register), method: :get, data: { turbo_frame: 'modal' }, class: 'button-style delete' %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/user_registers/index.html.erb
<div class="content-user">
  <h1>User Information Lists</h1>
  <%= button_to 'Register User', new_user_register_path, method: :get, class: 'button-style' %>
  <%= turbo_frame_tag "grid-conent" do %>
    <%= render "gridCardInfo"%>
  <% end %>
</div>
<%= turbo_frame_tag "modal" do %><%end%>

app/views/user_registers/new.html.erb
<div class="body">
  <div class="contener-content">
    <div class="form-style">
      <h1>Register Form</h1>
      <%= form_with model: @user_register, local: true, html: {class: 'form-regis'} do |form|%>
        <div class="row-form">
          <div class="form-content">
            <%= form.label :first_name, "First Name", class: "form-label"%>
            <%= form.text_field :first_name, class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:first_name].any? %>">
              <% @user_register.errors.full_messages_for(:first_name).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
          <div class="form-content">
            <%= form.label :last_name, "Last Name", class: "form-label"%>
            <%= form.text_field :last_name, class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:last_name].any? %>">
              <% @user_register.errors.full_messages_for(:last_name).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row-form">
          <div class="form-content">
            <%= form.label :birthday, "Birthday", class: "form-label"%>
            <%= form.date_field :birthday, class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:birthday].any? %>">
              <% @user_register.errors.full_messages_for(:birthday).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
          <div class="form-content">
            <%= form.label :gender, "Gender", class: "form-label"%>
            <div class="form-radio-group">
              <%= form.radio_button :gender, "male",class: 'form-radio' %>
              <%= form.label :gender_male, "Male",class: 'form-radio-label' %>
              <%= form.radio_button :gender, "female",class: 'form-radio' %>
              <%= form.label :gender_female, "Female",class: 'form-radio-label' %>
            </div>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:gender].any? %>">
              <% @user_register.errors.full_messages_for(:gender).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row-form">
          <div class="form-content">
            <%= form.label :email, "Email", class: "form-label"%>
            <%= form.email_field :email, class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:email].any? %>">
              <% @user_register.errors.full_messages_for(:email).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
          <div class="form-content">
            <%= form.label :phone_number, "Phone Number", class: "form-label"%>
            <%= form.telephone_field :phone_number, class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:phone_number].any? %>">
              <% @user_register.errors.full_messages_for(:phone_number).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row-form">
          <div class="form-content">
            <%= form.label :subject, "Subject",class: "form-label"%>
            <%= form.select :subject, options_for_select(@subjects),{},class: "form-input" %>
            <div class="error-messages <%= 'has-error' if @user_register.errors[:subject].any? %>">
              <% @user_register.errors.full_messages_for(:subject).each do |message| %>
                <div class="error-message"><%= message %></div>
              <% end %>
            </div>
          </div>
        </div>
        <div>
          <%= form.submit "Submit", class: "button-style" %>
        </div>
      <% end %>
    </div>
  </div>
</div>